const brands = [
  {
    id: "0-9",
    values: [
      "1800",
      "19 Crimes",
      "7UP"
    ]
  },
  {
    id: "A",
    values: [
      "Abelha",
      "Aberfeldy",
      "Aberlour",
      "Adnams",
      "Aero",
      "After Eight",
      "After Shock",
      "Agwa De Bolivia",
      "Air Wick",
      "Airwaves",
      "Akashi",
      "Alberto Balsam",
      "Alf Turner",
      "Alfieri",
      "Alka-Seltzer",
      "All-Bran",
      "Allinson's",
      "Alma",
      "Alpen",
      "Alpro",
      "Always",
      "Amarula",
      "Amber Leaf",
      "Ambrosia",
      "Americana",
      "Amoy",
      "Amstel",
      "Anadin",
      "Anchor",
      "Andrex",
      "Angel Delight",
      "Angels",
      "Angostura",
      "Antica",
      "Aperol",
      "Appletiser",
      "Appleton Estate",
      "Aptamil",
      "Aqua Pura",
      "Araldica",
      "Archers",
      "Arcoroc",
      "Ardbeg",
      "Ariel",
      "Ariztía",
      "Arla",
      "Asahi",
      "Ascheri",
      "Aspall",
      "Astonish",
      "Atora",
      "Auchentoshan",
      "Aunt Bessie's",
      "Avoca"
    ]
  },
  {
    id: "B",
    values: [
      "Babybel",
      "Bacardi",
      "Bacofoil",
      "Badger",
      "Bahlsen",
      "Baileys",
      "Baker Street",
      "Bakers",
      "Bakers Best",
      "Bakers Blend",
      "Balconi",
      "Bangla",
      "Banham",
      "Barefoot",
      "Barnstormer",
      "Barossa Ink",
      "Barr",
      "Barratt",
      "Batchelors",
      "Baxters",
      "Bear",
      "Becketts",
      "Beck's",
      "Becky's Bakery",
      "Beechams",
      "Beefsteak Club",
      "Béghin Say",
      "Bellingham",
      "Bell's",
      "Belvedere",
      "Belvita",
      "Ben & Jerry's",
      "Bénédictine",
      "Benson & Hedges",
      "Bentley",
      "Benylin",
      "Berkeley",
      "Bernard Matthews",
      "Berocca",
      "Betty Crocker",
      "Bic",
      "Big Al's",
      "Big D",
      "Big Time",
      "Bigga",
      "Billington's",
      "Bird in Hand",
      "Bird's",
      "Birds Eye",
      "BirraMoretti",
      "Birrificio Angelo Poretti",
      "Bisto",
      "Black Sheep",
      "Blakemans",
      "Blandy's",
      "Blossom Hill",
      "Blossom Soft",
      "blu",
      "Blue Dragon",
      "BlueRiband",
      "Boddingtons",
      "Boë",
      "Bold",
      "Bolero",
      "Bollinger",
      "Bols",
      "Bombay Sapphire",
      "Bonio",
      "Bonjela",
      "Bonne Maman",
      "Booker",
      "Boost",
      "Border",
      "Borders Gold",
      "Bosco",
      "Bottega",
      "Bottlegreen",
      "Bovril",
      "Bowmore",
      "Brain Licker",
      "Brancott Estate",
      "Branston",
      "Brasso",
      "BrewDog",
      "Bridor",
      "Brillo",
      "Brioche Pasquier",
      "Britvic",
      "Brooklyn Brewery",
      "Brugal",
      "Bruichladdich",
      "Bucks Fizz",
      "Bud Light",
      "Budějovický Budvar",
      "Budweiser",
      "Buffalo Trace",
      "Bulldog",
      "Bulleit",
      "Bulmers",
      "Bundaberg",
      "Bunnahabhain",
      "Burts",
      "Bushmills",
      "Butcher's",
      "Butterific",
      "Butterkist",
      "Buxton"
    ]
  },
  {
    id: "C",
    values: [
      "C.P.W.",
      "Cactus Jack's",
      "Cadbury",
      "Cafe Classic",
      "Café Maid",
      "Cafédirect",
      "Calgon",
      "Callebaut",
      "Calpol",
      "Calvet",
      "Calypso",
      "Camden Park",
      "Camel",
      "Campari",
      "Campo Dorado",
      "Campo Viejo",
      "Canadian Club",
      "Canderel",
      "Cane Trader",
      "Canti",
      "Cantine Di Ora",
      "Capri-Sun",
      "Captain Morgan",
      "Caputo",
      "Carex",
      "Carling",
      "Carlsberg",
      "Carlton",
      "Carnation",
      "Carousel",
      "Carr's",
      "Carte D'Or",
      "Carters",
      "Casa Roscoli",
      "Casa Sant' Orsola",
      "Caseificio Villa",
      "Casillero del Diablo",
      "Castel Regio",
      "Castella",
      "Castillo de Albai",
      "Caterers Pride",
      "Caterline",
      "Caterwrap",
      "Cathedral City",
      "Catsan",
      "Cawston Press",
      "Cazcabel",
      "CB",
      "Celebrations",
      "Cellier D'Or",
      "Cesar",
      "Chambord",
      "Chandon",
      "Chanoine",
      "Chapel Down",
      "Charcuti",
      "Chartreuse",
      "Château La Hourcade",
      "Châteauneuf-du-Pape",
      "Cheerios",
      "Cheetos",
      "Chef & Sommelier",
      "Chef William",
      "Chefs Brigade",
      "Chef's Essentials",
      "Chef's Larder",
      "Cherry B",
      "Cherry Valley",
      "Cherubs",
      "Chesterfield",
      "Chewits",
      "Chicago Town",
      "Chivas Regal",
      "Chocomel",
      "Christian Dupre",
      "Chupa Chups",
      "Cif",
      "Cillit Bang",
      "Cinzano",
      "Cirio",
      "Clan",
      "Clarks",
      "Classic",
      "Clean Pro+",
      "CleanPro",
      "CleanPro+",
      "Clearly",
      "Clipper",
      "Cloudy Bay",
      "Clover",
      "Cobra",
      "Coca-Cola",
      "Cockburn's",
      "Cockspur",
      "Cointreau",
      "Colgate",
      "Colla",
      "Colman's",
      "Colourworks",
      "Comelle",
      "Comfort",
      "Compass Box",
      "Compost Me",
      "Conditorei Coppenrath & Wiese",
      "Cooks & Co",
      "Cook's Matches",
      "Cool Shot",
      "Coolmore",
      "Coors",
      "Copper Dog",
      "Corn Flakes",
      "Cornetto",
      "Cornish Cheese Co.",
      "Corona",
      "Costa",
      "Cottage Bakery",
      "Country Life",
      "Country Manor",
      "Courvoisier",
      "Covonia",
      "Cow & Gate",
      "Cragganmore",
      "Craigellachie",
      "Craigmillar",
      "Cravendale",
      "Crisp 'n Dry",
      "Croft",
      "Crunch",
      "Crusha",
      "Cruzcampo",
      "Crystale",
      "Curiously",
      "Curtis",
      "Cutters Choice",
      "Cypressa"
    ]
  },
  {
    id: "D",
    values: [
      "Da Vinci Gourmet",
      "Daddies",
      "Daim",
      "Dairy Box",
      "Dairy Partners",
      "Dairylea",
      "Dalwhinnie",
      "d'Arenberg",
      "Dark Horse",
      "Daz",
      "De Cecco",
      "De Kuyper",
      "Deanston",
      "Deepio",
      "Delamere Dairy",
      "Delicatessen",
      "Delicatessen Fine Eating",
      "Delphi",
      "Desperados",
      "Dettol",
      "Devon Cream Company",
      "Dewar's",
      "Diablo",
      "Diet Coke",
      "Dinaclass",
      "Dingle",
      "Diplomático",
      "Disaronno",
      "Discos",
      "Diviande",
      "Dolce Gusto",
      "Dolce Mamma",
      "Dolmio",
      "Domestos",
      "Don Angel",
      "Don Julio",
      "Don Papa",
      "Doritos",
      "Douwe Egberts",
      "Dove",
      "DP",
      "Dr Pepper",
      "Dr. Oetker",
      "Dragon Soop",
      "Dragon Stout",
      "Drambuie",
      "Dreamies",
      "Driver's",
      "Drum",
      "Dubonnet",
      "Dunhill",
      "Duni",
      "Duracell",
      "Durex"
    ]
  },
  {
    id: "E",
    values: [
      "E&J",
      "Eager",
      "Eagle Rare",
      "Easy",
      "Eat Natural",
      "Echo Falls",
      "Eco",
      "Eco Products",
      "Edge",
      "Edler's",
      "Edmond Briottet",
      "Efes",
      "EGL",
      "El Dorado",
      "El Jimador",
      "El Mestengo",
      "Elastoplast",
      "Elbow Grease",
      "Elephant Atta",
      "Elka",
      "Ella's Kitchen",
      "Elmlea",
      "Embassy",
      "Encona",
      "English Cheesecake Company",
      "Enliven",
      "Erdinger",
      "Essentials",
      "Estrella Damm",
      "Euro Shopper",
      "Evian",
      "Exis",
      "Extra"
    ]
  },
  {
    id: "F",
    values: [
      "Fage",
      "Fairy",
      "Falcone",
      "Fallini Formaggi",
      "Fanta",
      "Farley's",
      "Farm Fresh",
      "Farm Frites",
      "Fattorie Garofalo",
      "Febreze",
      "Felix",
      "Fentimans",
      "Ferrero Rocher",
      "Fever-Tree",
      "Few Spirits",
      "Filippo Berio",
      "Finca",
      "Fini",
      "Finish",
      "Fiorello",
      "Fireball",
      "Fisherman's Friend",
      "Fixodent",
      "Fizz Wiz",
      "Flash",
      "Flipz",
      "Flora",
      "Florette",
      "Fontinella",
      "Food Connections",
      "FornoBonomi",
      "Fosters",
      "Foster's",
      "Fox's",
      "Frangelico",
      "Frank Cooper's",
      "Frank's RedHot",
      "Fray Bentos",
      "Freixenet",
      "French's",
      "Freshers",
      "Fridge Raiders",
      "Frisia",
      "Frobishers",
      "Frosties",
      "Frosty Jack's",
      "Frylight",
      "Fry's",
      "Fuel Express",
      "Fulfil",
      "Fuller's",
      "Funkin",
      "FunkinPro",
      "Funtime",
      "Fyffes",
      "FyNite"
    ]
  },
  {
    id: "G",
    values: [
      "G.H. Mumm",
      "Gabbia D Oro",
      "Galaxy",
      "Galbani",
      "Gale's",
      "Galliano",
      "Gallo",
      "Gallo Family Vineyards",
      "Galpharm",
      "Garden Gourmet",
      "Garden Pride",
      "Gaviscon",
      "Gazebo Cuisine",
      "Geeta's",
      "Gia",
      "Gillette",
      "Glade",
      "Glayva",
      "Glen Moray",
      "Glenfiddich",
      "Glengoyne",
      "Glenkinchie",
      "Glenmorangie",
      "Go-Cat",
      "Gold Block",
      "Gold Leaf",
      "Golden Acre",
      "Golden Crumb",
      "Golden Virginia",
      "Golden Wonder",
      "Goldenfry",
      "Goldfish",
      "Gomo",
      "Good Boy",
      "Goodfella's",
      "Goodwyns",
      "Gordon's",
      "Gourmet",
      "Gourmet Pidy",
      "Grace",
      "Gran Moravia",
      "Grana Padano",
      "Grand Fermage",
      "Grand Marnier",
      "Granja Tres Arroyos",
      "Grant's",
      "Gratien & Meyer",
      "Gray's",
      "Green Giant",
      "Green Spot",
      "Greene King",
      "Greens",
      "Grenade",
      "Gressingham",
      "Grey Goose",
      "Grumpy Mule",
      "Guinness"
    ]
  },
  {
    id: "H",
    values: [
      "Haden",
      "Haig",
      "Hakushu Distiller's Reserve",
      "Halls",
      "Hall's",
      "Hamlet",
      "Hannah's",
      "Happy Shopper",
      "Hardys",
      "Haribo",
      "Harpic",
      "Harringtons",
      "Harrisons",
      "Hartley's",
      "Harveys",
      "Havana Club",
      "Head & Shoulders",
      "Healeys",
      "Heets",
      "Heineken",
      "Heinz",
      "Hellmann's",
      "Henna",
      "Hennessy",
      "Henri Wintermans",
      "Henry Goode's",
      "Henry Jones",
      "Henry Westons",
      "Hermesetas",
      "Hero",
      "Hershey's",
      "Hibiki",
      "Hidden Road",
      "High Commissioner",
      "Highbridge",
      "Highland Park",
      "Highland Spring",
      "Hill Farm",
      "Hobgoblin",
      "Holborn",
      "Holsten",
      "Holts",
      "Honey Monster",
      "Horlicks",
      "Hotos",
      "Houghton Hams",
      "Hovis",
      "HP",
      "Hpnotiq",
      "Hubba Bubba",
      "Huggies",
      "Hula Hoops"
    ]
  },
  {
    id: "I",
    values: [
      "I Can't Believe It's Not Butter!",
      "I Heart",
      "Ice Breakers",
      "Ice Valley",
      "Imodium",
      "Imperial Leather",
      "Impulse",
      "Inch's",
      "Infiniti",
      "Infinity",
      "Innocent",
      "Irn-Bru",
      "Isla Negra",
      "Itac",
      "Italia",
      "Ivory Ledoux"
    ]
  },
  {
    id: "J",
    values: [
      "J.L. Quinson",
      "J2O",
      "Jack Daniel's",
      "Jack Link's",
      "Jack Rabbit",
      "Jack's",
      "Jacobs",
      "Jacob's",
      "Jägermeister",
      "Jakemans",
      "Jam Shed",
      "Jameson",
      "JammieDodgers",
      "Jelly Belly",
      "Jena",
      "Jif",
      "Jim Beam",
      "John Player Special",
      "John Smith's",
      "John West",
      "Johnnie Walker",
      "Johnson's",
      "Johnson's Baby",
      "Jolly Rancher",
      "Jordans",
      "Jose Cuervo",
      "JP. Chenet",
      "JPS",
      "Jucee",
      "Juice Burst",
      "Jura",
      "Jus-Rol",
      "Just Bacon",
      "Just Eau",
      "Just Love Food Company"
    ]
  },
  {
    id: "K",
    values: [
      "K",
      "KA",
      "Kahlua",
      "Kellogg's",
      "Kenco",
      "Kerry Dairy",
      "Kerrygold",
      "Kerrymaid",
      "Kershaws",
      "Kettle",
      "Kettyle",
      "Kind",
      "Kinder",
      "King Edward",
      "Kingfisher",
      "Kingston",
      "KitKat",
      "Kleenex",
      "Knorr",
      "Kohinoor",
      "Koko Kanu",
      "Ko-Lee",
      "Kopparberg",
      "Kotex",
      "KP",
      "Kraft",
      "Krave",
      "Kronenbourg 1664",
      "KTC",
      "Kühne",
      "Kwai Feh",
      "Kylie Minogue"
    ]
  },
  {
    id: "L",
    values: [
      "La Baume",
      "La Boulangère",
      "La Pintora",
      "La Vieille Ferme",
      "Lagavulin",
      "Lakeland",
      "Lakeland Dairies",
      "Lamb Weston",
      "Lambert & Butler",
      "Lambrini",
      "Lamb's",
      "Lancashire Farm",
      "Lands",
      "Lanson",
      "Laphroaig",
      "Laurent-Perrier",
      "Lavazza",
      "Lea & Perrins",
      "Lee Kum Kee",
      "Lees",
      "Lees'",
      "Leffe",
      "Lemsip",
      "Les Brioches",
      "Levi Roots",
      "Lichfield",
      "Lichfields",
      "Limoncello",
      "Lindt",
      "Lion",
      "Lipton",
      "Little Town Dairy",
      "Lloytron",
      "Lockets",
      "L'OR",
      "Los Picos Distantes",
      "LoSalt",
      "Lotus",
      "Louis Latour",
      "Loyd Grossman",
      "LU",
      "Luc Belaire",
      "Lucky Dragon Brand",
      "Lucky Strike",
      "Lucozade",
      "Lurpak",
      "Lux",
      "Luxardo",
      "Lyle's",
      "Lynx"
    ]
  },
  {
    id: "M",
    values: [
      "M&M's",
      "Macphie",
      "Maestro",
      "Maggi",
      "Magners",
      "Magnum",
      "Maille",
      "Maitre André",
      "Maker's Mark",
      "Maldon",
      "Malibu",
      "Maltesers",
      "Maoam",
      "Marcel Hubert",
      "Margaret's Country Kitchen",
      "Marigold",
      "Marisco Vineyards",
      "Marlboro",
      "Marmite",
      "Marques de la Sardana",
      "Marquis de Rothberg",
      "Mars",
      "Marston's",
      "Martell",
      "Martini",
      "Marvel",
      "Maryland",
      "Mason & Miller",
      "Mateus",
      "Mattessons",
      "Maxwell House",
      "Mayfair",
      "Maynards Bassetts",
      "McCain",
      "McCoy's",
      "McDougalls",
      "McEwan's",
      "McGuigan",
      "McVitie's",
      "McWhinney's Sausages",
      "Meadowland",
      "Mekong",
      "Menissez",
      "Mentos",
      "Messer Schmitt",
      "Michter's",
      "Middleton Foods",
      "Midland Snacks",
      "Midori",
      "Mighty",
      "Mikado",
      "Milfresh",
      "Milka",
      "Milky Way",
      "Milkybar",
      "Millac Maid",
      "Milton",
      "Mirabeau",
      "Mission",
      "Moët & Chandon",
      "Mogu Mogu",
      "Mona Lisa",
      "Monin",
      "Monkey Shoulder",
      "Monster",
      "Monster Energy",
      "Monte Alban",
      "Montepulciano D'Abruzzo",
      "Monterey Jack",
      "Mornflake",
      "Most Wanted",
      "Mount Gay",
      "Mountain Dew",
      "Mountain Mist",
      "Mozart",
      "Mr Kipling",
      "Mr Muscle",
      "Mr. Black",
      "Mr. Freeze",
      "Mr. Tom",
      "Mrs Crimble's",
      "Mrs Elswood",
      "Muckypups",
      "Mud House",
      "Müller",
      "Munchies",
      "Muscat de St Jean de Minervois",
      "Mutti",
      "Mythos"
    ]
  },
  {
    id: "N",
    values: [
      "Nākd",
      "Naked",
      "Nando's",
      "Napolina",
      "Natco",
      "Nature Valley",
      "Nature's Finest",
      "Nerds",
      "Nescafe",
      "Nescafé",
      "Nesquik",
      "Newcastle Brown Ale",
      "Newman's Own",
      "Nic",
      "Nickelodeon",
      "Nik Naks",
      "Nikka Whisky",
      "Nilco",
      "Nissin",
      "Nivea",
      "Nobby's",
      "Nobilo",
      "Noel's",
      "Nomadic",
      "Nortech Foods Limited",
      "Numatic International",
      "Nurofen",
      "Nuromol",
      "Nutella",
      "NYCoffee",
      "Nyetimber"
    ]
  },
  {
    id: "O",
    values: [
      "Oak Crown",
      "Oasis",
      "Oatly",
      "Oban",
      "OCB",
      "Ocean Pearl",
      "Ocean Spray",
      "Old Bay",
      "Old El Paso",
      "Old Holborn",
      "Old Jamaica",
      "Old Mout Cider",
      "Old Pulteney",
      "Old Speckled Hen",
      "Olive King",
      "Olmeca",
      "Omega",
      "Onken",
      "Opies",
      "Options",
      "Oranjeboom",
      "Oreo",
      "Organix",
      "Orient",
      "Ouzo 12",
      "Oxo",
      "Oyster Bay"
    ]
  },
  {
    id: "P",
    values: [
      "Paco & Lola",
      "Pal TX",
      "Palazzo",
      "Pall Mall",
      "Palmax",
      "Pampers",
      "Panadol",
      "Panama",
      "Paragon",
      "Paramount",
      "Parma",
      "Parmigiano Reggiano",
      "Parsons",
      "Passoã",
      "Patak's",
      "Paté Grand-Mére",
      "Paterson's Grove",
      "Patrick Chodot",
      "Patrón",
      "Paul Langier",
      "Paxo",
      "Paysan Breton",
      "Pearl Delights",
      "Pedigree",
      "Peka",
      "Peperami",
      "Peppa Pig",
      "Peppadew",
      "Pepsi",
      "Père Magloire",
      "Pernod",
      "Peroni",
      "Persil",
      "PG Tips",
      "Philadelphia",
      "Picpoul de Pinet",
      "Pidy",
      "Pierre Brévin",
      "Pig's Nose",
      "Pimm's",
      "Piriteze",
      "Pizza Express",
      "Pledge",
      "Plenty",
      "Polo",
      "Pom-Bear",
      "Ponticello",
      "Popchips",
      "Poppies",
      "Port Salut",
      "Porta 6",
      "Pot Noodle",
      "Powerade",
      "Preema",
      "Premium Choice",
      "Président",
      "Prestige de Calvet",
      "Pretty",
      "Previata",
      "Prime",
      "Primula",
      "Princes",
      "Princess",
      "Pringles",
      "Professional",
      "Prosecco",
      "Pukka",
      "Pura",
      "Purdey's",
      "Purina",
      "Purina ONE"
    ]
  },
  {
    id: "Q",
    values: [
      "QC",
      "Quaker",
      "Quality",
      "Quality Street",
      "Quirky Bird",
      "Quorn"
    ]
  },
  {
    id: "R",
    values: [
      "R Whites",
      "Radox",
      "Raid",
      "Ramon",
      "Rational",
      "Raw",
      "Raymond Huet",
      "Ready Brek",
      "Real Lancashire",
      "Red Alert",
      "Red Bull",
      "Red Gum Creek",
      "Red Stripe",
      "Redbreast",
      "RedLeg",
      "Reese's",
      "Regal",
      "Reggia",
      "Regimental",
      "Regina",
      "Rekorderlig",
      "Relentless",
      "Rémy Martin",
      "Rennie",
      "Ribena",
      "Richmond",
      "Riesen",
      "Rio",
      "Ritz",
      "Rizla",
      "Robert Scott & Sons",
      "Robinsons",
      "Rockstar",
      "Rodda's",
      "Rolo",
      "Rombouts",
      "Ron Zacapa",
      "Roquito",
      "Rose's",
      "Rothmans",
      "Rowntree's",
      "Rowse",
      "Royal Crown",
      "Royal Dane",
      "Royal Dutch",
      "Royal Mail",
      "Royal Salute",
      "Royals",
      "Roysters",
      "Rubicon",
      "Rustlers",
      "Ryvita"
    ]
  },
  {
    id: "S",
    values: [
      "S.Pellegrino",
      "Sabert",
      "Sabichi",
      "Sagatiba",
      "Sailor Jerry",
      "San Andres",
      "San Marco",
      "San Pellegrino",
      "SanMiguel",
      "Sanpellegrino",
      "Santa Maria",
      "Santa Marta",
      "Sarson's",
      "Saxon's",
      "Sazerac Rye",
      "Scenic Ridge",
      "Schwartz",
      "Schweppes",
      "Seabrook",
      "Seachill",
      "Seedlip",
      "Señorío de Chical",
      "Seriously Tasty",
      "Sesame Snaps",
      "Seven Tenths",
      "Shackleton",
      "Sharp's Brewery",
      "Sharwood's",
      "Sheba",
      "Sheep Dip",
      "Ship",
      "Shirevale",
      "Shredded Wheat",
      "Shreddies",
      "Sidoli",
      "Sierra",
      "Signature",
      "Silk Cut",
      "Silver Spoon",
      "Simple",
      "Simply",
      "Simply Fruity",
      "Singha",
      "Skips",
      "Skittles",
      "Slush Puppie",
      "SMA",
      "Smart Choice",
      "Smarties",
      "Smirnoff",
      "Smiths",
      "Smokehead",
      "Snacksters",
      "Snax on the Go",
      "Snickers",
      "Snow Shock",
      "Soignon",
      "Sol",
      "Solero",
      "Somersby",
      "Soreen",
      "Sour Patch Kids",
      "Sourz",
      "Southern Comfort",
      "Sovereign",
      "Spaas",
      "Space Raiders",
      "Spam",
      "Special K",
      "Speyburn",
      "Spitfire",
      "Sprite",
      "Squares",
      "St Hallett",
      "St Michel",
      "St Pierre",
      "St. Bruno",
      "Stagg Chili",
      "Star of the Sea",
      "Starbucks",
      "Starburst",
      "Staropramen",
      "Stella Artois",
      "Steradent",
      "Sterilgarda",
      "Sterling",
      "St-Germain",
      "Stoddarts of Scotland",
      "Stokes",
      "Stoneleigh",
      "Stone's",
      "Stork",
      "Stormhoek",
      "Stowford Press",
      "Strathmore",
      "Strepsils",
      "Strongbow",
      "Stronghold",
      "Sudafed",
      "Summer County",
      "Sun Exotic",
      "Sunmagic",
      "Sun-Pat",
      "Sunpride",
      "Super Bright",
      "Superkings",
      "Supermalt",
      "Supreme",
      "Sure",
      "Surf",
      "Swan",
      "Sweetex",
      "SweetZone",
      "Swizzels",
      "Symonds"
    ]
  },
  {
    id: "T",
    values: [
      "Tails",
      "Taj Mahal",
      "Talisker",
      "Tamnavulin",
      "Tampax",
      "Tango",
      "Tassimo",
      "Tate & Lyle",
      "Taylor's",
      "Taylors of Harrogate",
      "TC",
      "Teapigs",
      "Teeling",
      "Tequila Rose",
      "Terry's",
      "Tetley",
      "Tex Chunks",
      "TGI Fridays",
      "Thatchers",
      "The Ardmore",
      "The Balvenie",
      "The Bury Black Pudding Company",
      "The Chita",
      "The Dalmore",
      "The Famous Grouse",
      "The Glenlivet",
      "The Great British Pudding Company",
      "The Ice Co",
      "The Imokilly Cheese Company",
      "The Jacobite",
      "The King's Wrath",
      "The Kraken",
      "The London Essence Co.",
      "The Macallan",
      "The Secretary Bird",
      "The Shy Pig",
      "The Singleton",
      "The Tofoo Co.",
      "The Yamazaki",
      "Thomas",
      "Thorntons",
      "Three Barrels",
      "Tia Maria",
      "Tiama",
      "Tiburtina",
      "Tic Tac",
      "Tiger",
      "Tiger Tiger",
      "Tilda",
      "Tim Adams",
      "Timothy Taylor's",
      "Ting",
      "Tipiak",
      "Tobermory",
      "Toffee Crisp",
      "Togouchi",
      "Tohfa",
      "Toki",
      "Tork",
      "Torres",
      "Toxic Waste",
      "Tracker",
      "Trebor",
      "Trek",
      "Trex",
      "Triple Diamond",
      "Trivento",
      "Trophy",
      "Tropicana",
      "Tsarine",
      "Tunnock's",
      "Tusk",
      "Tusker",
      "Tuxford & Tebbutt",
      "Twinings",
      "Twister",
      "Twix",
      "Tyrrells",
      "Tyskie"
    ]
  },
  {
    id: "U",
    values: [
      "U Brands",
      "U Group",
      "U Group Ltd",
      "ÜFIT",
      "UM",
      "Unbranded",
      "Unigloves",
      "Universal",
      "Utterly Butterly"
    ]
  },
  {
    id: "V",
    values: [
      "Valpolicella",
      "Vanish",
      "Vaseline",
      "Vasse Felix",
      "Vecchia Romagna",
      "Velo",
      "Velvet",
      "Ventisquero",
      "Venus",
      "Vernieres",
      "Veroni",
      "Vertmont",
      "Very Lazy",
      "Veuve Clicquot",
      "Viakal",
      "Vicks",
      "Vidal",
      "Viennetta",
      "Villa Maria",
      "Vimto",
      "Vin D'Alsace",
      "Vini dei Cardinali",
      "Vino Spumante",
      "Violife",
      "Vista dei Cipressi",
      "Viva",
      "VK",
      "VO5",
      "Vogue",
      "Volvic",
      "Vrysaki"
    ]
  },
  {
    id: "W",
    values: [
      "Wagg",
      "WagonWheels",
      "Wainwright",
      "Wairau Cove",
      "Walkers",
      "Warburtons",
      "Warninks",
      "Waverley",
      "Webbox",
      "Weetabix",
      "Weetos",
      "Werther's Original",
      "Westaways",
      "Wham",
      "Wheat Crunchies",
      "Whirlz",
      "Whiskas",
      "Whispering Angel",
      "Whitefurze",
      "Whitworths",
      "Whole Earth",
      "Whyte & Mackay",
      "Wichmann",
      "Wikinger",
      "Wild Turkey",
      "Wildlife",
      "Willow",
      "Winalot",
      "Windsor",
      "Windsor Blue",
      "Winston",
      "Wisdom",
      "WKD",
      "Wolf Blass",
      "Woodford Reserve",
      "Wood's",
      "Wrapmaster",
      "Wray & Nephew",
      "Wright's",
      "Wychwood Brewery",
      "Wyke Farms"
    ]
  },
  {
    id: "X",
    values: []
  },
  {
    id: "Y",
    values: [
      "Yamas!",
      "Yazoo",
      "Yellow Spot",
      "Yellow Tail",
      "Yorkie",
      "Yorkshire Tea",
      "Young's"
    ]
  },
  {
    id: "Z",
    values: [
      "Zig-Zag",
      "Zoflora",
      "Zubr"
    ]
  }
];
