const classification = {
  '1A': '1A - GROCERY GENERAL STORE',
  '1C': '1C - DELICATESSEN STORES',
  '1D': '1D - DAIRYMEN',
  '1F': '1F - BUTCHERS',
  '1G': '1G - GREENGROCERS',
  '1J': '1J - FISHMONGERS',
'1K': '1K - BAKERY SHOP',
'4A': '4A - NON-FOOD STORES',
'4B': '4B - FARM SHOPS',
'4C': '4C - CHEMIST/HEALTH SHOPS',
'4D': '4D - PET SHOPS',
'4E': '4E - CINEMAS',
'4F': '4F - DVD RENTAL STORES',
'4J': '4J - VENDING',
'5A': '5A - STREET MARKET',
'SH': 'SH - Non-Classified Food Retailer  DO NOT USE',
'6A': '6A - IND FOOD DEL SERVICE',
'6B': '6B - IND WHOLESALER',
'6C': '6C - WHOLESALE CHAIN',
'2A': '2A - OFF LICENCE',
'3A': '3A - CTN (CIG/TOB/NEWS)',
'3B': '3B - GARAGE FORECOURTS',
'AA': 'AA - PUB NO FOOD',
'AB': 'AB - PUB WITH FOOD',
'AD': 'AD - PUB WITH ACCOMM',
'DC': 'DC - WINE BAR/BISTRO',
'JA': 'JA - WMC/SPORTS CLUBS',
'JC': 'JC - NIGHT CLUB',
'DA': 'DA - BEST FOOD LOGISTICS',
'DF': 'DF - ITALIAN RESTAURANT',
'DH': 'DH - CHINESE RESTAURANT',
'DJ': 'DJ - INDIAN RESTAURANT',
'DK': 'DK - OTHER RESTAURANTS',
'DM': 'DM - AMERICAN / SOUTH AMERICAN RESTAURANT',
'DN': 'DN - BRITISH/IRISH RESTAURANT',
'DP': 'DP - OTHER EUROPEAN RESTAURANT',
'DQ': 'DQ - OTHER ASIAN / MID EASTERN / AFRICAN',
'CE': 'CE - HOLIDAY CENTRE',
'HA': 'HA - ROADSIDE RESTAURANT',
'HC': 'HC - BUS/COACH/RAIL CATR',
'JB': 'JB - LEISURE CENTRE',
'JD': 'JD - TOURIST ATTRACTION',
'JE': 'JE - OUTSIDE EVENT CATER',
'U6': 'U6 - BOOKER NATIONAL ACCOUNTS',
'U7': 'U7 - Non-Classified Horeca (DO NOT USE)',
'CA': 'CA - HOTEL',
'CB': 'CB - GUEST HOUSE',
'CD': 'CD - HOSTEL',
'BA': 'BA - FISH & CHIPS',
'BC': 'BC - CHINESE TAKEAWAY',
'BD': 'BD - INDIAN TAKEAWAY',
'BE': 'BE - GREEK/KEBEB TAKEAWAY',
'BF': 'BF - FAST FOOD TAKEAWAY',
'BG': 'BG - PIZZA TAKEAWAY/DEL',
'BB': 'BB - BAKERS/SANDWICHES',
'BH': 'BH - CAFE',
'HB': 'HB - TRANSPORT CAFE/VAN',
'GA': 'GA - SCHOOL LOCAL AUTH',
'GC': 'GC - SCHOOL - PRIVATE',
'GD': 'GD - HIGHER EDUCATION',
'JF': 'JF - SCOUTS/GUIDES',
'1N': '1N - ARAMARK PRISON SERV',
'1P': '1P - ARAMARK - OTHER',
'1R': '1R - ARAMARK - B&I',
'1S': '1S - ARAMARK - CORPORATE',
'1T': '1T - ARAMARK - DEFENCE',
'1U': '1U - ARAMARK - EDUCATION',
'1V': '1V - ARAMARK - HEALTHCARE',
'1W': '1W - ARAMARK - JUDICIAL',
'1X': '1X - ARAMARK - CPS',
'FA': 'FA - HOSPITAL NHS',
'FC': 'FC - HOSPITAL PRIVATE',
'FE': 'FE - NURSING HOME PRIVATE',
'FF': 'FF - NURSING HOME CHARITY',
'FG': 'FG - INSTITUTIONS/PRISONS',
'EA': 'EA - CANTEEN FACILITY',
'EB': 'EB - OFFICE SUPPLIES',
'EC': 'EC - PUBLIC SERVICES CANT',
'ED': 'ED - ARMED SERVICES',
'JG': 'JG - UNLICENCED CLUBS',
'1L': '1L - ICELAND',
'7E': '7E - MAKRO INTER COMPANY',
'7F': '7F - RITTER INTER COMPANY',
'7G': '7G - CLASSIC INTER COMPANY',
'7H': '7H - BRP INTERCOMPANY',
'7I': '7I - BFL INTER COMPANY',
'1E': '1E - EXPORT',
'4G': '4G - NON FOOD/CAR SALES',
'7A': '7A - OTHER - COLLEAGUES',
'7B': '7B - BAUGUR PARTNERS',
'7C': '7C - FAMILY AND FRIENDS',
'7D': '7D - PENSIONER',
'8A': '8A - DAY PASS',
'8B': '8B - DAYPASS BRANCH B',
'8C': '8C - DAYPASS BRANCH C',
'8D': '8D - DAYPASS BRANCH D',
'8E': '8E - DAYPASS BRANCH E',
'8F': '8F - DAYPASS BRANCH F',
'1Q': '1Q - DELIVERED RETAILERS',
'1Z': '1Z - TEMPORARY CATEGORY',
'9X': '9X - EX CUSTOMER',
'9Z': '9Z - OTHER',
'X1': 'X1 - Belfast Public Off License',
'X2': 'X2 - Carpet Commission',
'X3': 'X3 - Daily Card',
'X4': 'X4 - Daily Card - International Visitor',
'X5': 'X5 - Deleted Account (ask business to re-regi',
'X6': 'X6 - Lottery Agent',
'X7': 'X7 - Makro Supplier',
'X8': 'X8 - Makro UK Online Sales',
'X9': 'X9 - Makro UK Public Outlet',
'XA': 'XA - MCafe Purchases',
'XB': 'XB - Metro Internal Consumption',
'XC': 'XC - Metro Staff Store',
'XD': 'XD - Repair Service',
'XE': 'XE - Sales To Customers Of Other Stores',
'XF': 'XF - Non-Classified SMEs',
'CH': 'CH - CHARITY',
'NM': 'NM - Chef Central Non Member',
'TE': 'TE - Tesco',
'EE': 'EE - OFF SHORE',
'P2': 'P2 - TRADESMAN',
'P3': 'P3 - TRNSPRT (TAXI/COACH)',
'P4': 'P4 - PUBLIC SERVICE',
'P5': 'P5 - OTHER BUSINESS',
'P6': 'P6 - CORPORATE (> 50 EMP)',
'V1': 'V1 - Building Maintenance',
'V2': 'V2 - Electrical Contractor / Electrician',
'V3': 'V3 - Garden Maintenance',
'V4': 'V4 - Hairdresser',
'V5': 'V5 - Metal Worker',
'V6': 'V6 - Other Craftsmen',
'V7': 'V7 - Painter / Decorator',
'V8': 'V8 - Plumber',
'V9': 'V9 - Roofer / Carpenter',
'VA': 'VA - Tailor / Dress Maker',
'VB': 'VB - Vehicle Maintenance',
'VC': 'VC - Dentists',
'VD': 'VD - Doctors',
'VE': 'VE - Hospital',
'VF': 'VF - Medical Specialists',
'VG': 'VG - Other Healthcare',
'VH': 'VH - Social Care Institution',
'VJ': 'VJ - Agriculture',
'VK': 'VK - Building Construction',
'VL': 'VL - Extraction',
'VM': 'VM - Food Production',
'VN': 'VN - Non Food Production',
'VP': 'VP - Other Industries',
'VQ': 'VQ - Utilities (Gas / Electric / Telephone et',
'VR': 'VR - Art / Culture',
'VS': 'VS - Associations / Clubs (Without Alcohol Li',
'VT': 'VT - Charity / Religious Group',
'VU': 'VU - Education / Science',
'VW': 'VW - Government & Administration',
'VX': 'VX - Other Institutions',
'VY': 'VY - Chemist',
'VZ': 'VZ - Department Store',
'W1': 'W1 - Florist',
'W2': 'W2 - Furniture Retailer',
'W3': 'W3 - Hardware / DIY Retailer',
'W4': 'W4 - Internet Retailer',
'W5': 'W5 - Jewellery Retailer',
'W6': 'W6 - Other High Street Non Food Retail Outlet',
'W7': 'W7 - Pet Shop',
'W8': 'W8 - Shoe Retailer',
'W9': 'W9 - Sports Goods Retailer',
'WA': 'WA - Stationery Retailer',
'WB': 'WB - Vehicle Dealership',
'WC': 'WC - Finance / Insurance / Consultancy',
'WD': 'WD - Internet & Computer Services',
'WE': 'WE - Liberal Profession',
'WF': 'WF - Other Agencies',
'WG': 'WG - Other Office Based Services',
'WH': 'WH - Sales Agent',
'WJ': 'WJ - Commercial Cleaning',
'WK': 'WK - Copy Shop',
'WL': 'WL - Event Management Services',
'WM': 'WM - Hire Services',
'WN': 'WN - Other Physical Services',
'WP': 'WP - Pet Care',
'WQ': 'WQ - Photographer',
'WR': 'WR - Post / Courier',
'WS': 'WS - Printing / Sign Writing',
'WT': 'WT - Taxi',
'WU': 'WU - Transport Logistics',
'WV': 'WV - Beauty',
'WW': 'WW - Complementary Therapy',
'WX': 'WX - Other Wellness',
'WY': 'WY - Spa',
'WZ': 'WZ - Sports / Recreation Centre (Without Alco)'	
}
